# SPDX-License-Identifier: Apache-2.0
groups:
- name: cluster_resource
  rules:
    - record: kubernetes:cluster_resources:total_requests
      expr: |
        sum by (instance, resource) (
          kube_pod_container_resource_requests
          - on(instance, namespace, pod) group_left max(kube_pod_status_phase{phase=~"Succeeded|Failed"}) by (instance, namespace, pod)
        )
    - record: kubernetes:cluster_resources:total_limits
      expr: |
        sum by (instance, resource) (
          kube_pod_container_resource_limits
          - on(instance, namespace, pod) group_left max(kube_pod_status_phase{phase=~"Succeeded|Failed"}) by (instance, namespace, pod)
        )
