Metrics/LineLength:
  Max: 159

Style/BlockDelimiters:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

