profile::contacts::role_contacts: ['Infrastructure Foundations']
profile::configmaster::server_name: config-master.wikimedia.org
profile::configmaster::server_aliases:
  - 'config-master.discovery.wmnet'
  - "config-master.%{::site}.wmnet"
  - "%{facts.networking.fqdn}"
profile::configmaster::enable_nda: true
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::global_cert_name: "%{alias('profile::configmaster::server_name')}"
profile::tlsproxy::envoy::cfssl_options:
  hosts: "%{alias('profile::configmaster::server_aliases')}"

profile::discovery::path: "/srv/config-master/discovery"
