profile::configmaster::server_name: config-master.wikimedia.org
profile::configmaster::server_aliases:
  - 'config-master.discovery.wmnet'
  - "config-master.%{::site}.wmnet"
profile::configmaster::enable_nda: true
