profile::contacts::role_contacts:
  - 'Observability'

cluster: prometheus
profile::resolving::domain_search:
  - wikimedia.org
  - eqiad.wmnet
  - codfw.wmnet
  - esams.wmnet
  - ulsfo.wmnet
  - eqsin.wmnet
  - drmrs.wmnet
prometheus::server::mysqld_exporter::mysql::host: db1215.eqiad.wmnet
prometheus::server::mysqld_exporter::mysql::port: 3306
prometheus::server::mysqld_exporter::mysql::database: zarcillo
prometheus::server::mysqld_exporter::mysql::user: prometheus-mysqld-exporter
# prometheus::server::mysqld_exporter::mysql::password: stored on the private repo

profile::prometheus::enable_thanos_upload: true

profile::prometheus::rsyncd::ensure: present

# Thanos will ask Prometheus (via Thanos Sidecar) for last 15d only
profile::prometheus::thanos::min_time: '-15d'

# The single host that's running Pushgateway.
# DNS prometheus-pushgateway.discovery.wmnet must match.
profile::prometheus::pushgateway_host: 'prometheus1005.eqiad.wmnet'

profile::lvs::realserver::use_conftool: true
profile::lvs::realserver::pools:
  prometheus:
    services:
      - prometheus@analytics
      - prometheus@k8s
      - prometheus@k8s-dse
      - prometheus@k8s-mlserve
      - prometheus@k8s-mlstaging
      - prometheus@k8s-staging
      - prometheus@ops
      - prometheus@services
      - apache2

profile::envoy::ensure: present
profile::tlsproxy::envoy::services:
   - server_names:
     - 'prometheus'
     - 'prometheus-eqiad.wikimedia.org'
     - 'prometheus-codfw.wikimedia.org'
     - 'prometheus-esams.wikimedia.org'
     - 'prometheus-ulsfo.wikimedia.org'
     - 'prometheus-eqsin.wikimedia.org'
     - 'prometheus-drmrs.wikimedia.org'
     port: 80
     cert_name: 'prometheus.wikimedia.org'
profile::tlsproxy::envoy::use_remote_address: true
profile::tlsproxy::envoy::sni_support: 'strict'
