# SPDX-License-Identifier: Apache-2.0
profile::alertmanager::irc::nickname: 'jinxer-wm-test'
profile::alertmanager::irc::nickname_password: 'dummy'
profile::alertmanager::irc::channel: 'wikimedia-o11y-test'

profile::alertmanager::web::vhost: "alerts.%{lookup('public_domain')}"

alertmanagers: "%{alias('__hosts_for_role_alerting_host')}"

profile::alertmanager::active_host: "%{alias('__master_for_role_alerting_host')}"
profile::alertmanager::partners: "%{alias('__hosts_for_role_alerting_host')}"
profile::alertmanager::grafana_hosts: "%{alias('__hosts_for_role_grafana')}"
profile::alertmanager::thanos_query_hosts: "%{alias('__hosts_for_role_thanos__frontend')}"

profile::alertmanager::sink_notifications: true
