---
profile::admin::groups:
  - wmcs-roots

# prometheus-pdns-exporter is scraped by cloudmetrics
# prometheus-node-exporter by prod servers
prometheus_nodes:
  - cloudmetrics1003.eqiad.wmnet
  - cloudmetrics1004.eqiad.wmnet
  - prometheus1005.eqiad.wmnet
  - prometheus1006.eqiad.wmnet

contactgroups: wmcs-team-email

cluster: wmcs
profile::prometheus::memcached_exporter::arguments: "--memcached.address=localhost:11000"
# See T224828
raid::md::timer_ensure: absent
profile::contacts::role_contacts: ["WMCS"]

# TODO: not required after the whole control plane is on the next network setup
# This is here to force designate to talk to cloudcontrol using the cloud-private link
# for things like galera and memcached
profile::openstack::eqiad1::openstack_controllers:
  - cloudcontrol1005.private.eqiad.wikimedia.cloud
  - cloudcontrol1006.private.eqiad.wikimedia.cloud
  - cloudcontrol1007.private.eqiad.wikimedia.cloud

profile::openstack::eqiad1::pdns::hosts:
  - auth_fqdn: ns1.openstack.eqiad1.wikimediacloud.org
    private_fqdn: cloudservices1006.private.eqiad.wikimedia.cloud
    host_fqdn: cloudservices1006.eqiad.wmnet
  - auth_fqdn: ns0.openstack.eqiad1.wikimediacloud.org
    private_fqdn: cloudservices1005.private.eqiad.wikimedia.cloud
    host_fqdn: cloudservices1005.eqiad.wmnet

profile::openstack::base::pdns::default_soa_content: ns0.openstack.eqiad1.wikimediacloud.org
profile::openstack::base::pdns::recursor::bgp_vip: 172.20.255.1

profile::dbbackups::mydumper::enabled: true
profile::dbbackups::mydumper::schedule: '*-*-* 00:00:00'
profile::dbbackups::mydumper::config: 'profile/openstack/base/dbbackups/pdns.cnf.erb'

# a few different domains that designate serves as authoritative
profile::openstack::eqiad1::pdns::auth::service::monitor_verify_records:
  - login.toolforge.org
  - k8s.svc.tools.eqiad1.wikimedia.cloud
  - tools-sgegrid-master.tools.eqiad1.wikimedia.cloud
  - www.wmcloud.org

profile::bird::advertise_vips:
  # NOTE: this is a shared BGP-based anycast VIP. There also a non-shared per-host adddress
  ns-recursor.openstack.eqiad1.wikimediacloud.org:
    ensure: present
    service_type: "pdns recursor"
    address: 172.20.255.1
    check_cmd: "/usr/lib/nagios/plugins/check_dns_query -H 172.20.255.1 -d www.wikimedia.org -t 1"
