profile::admin::groups:
  - wmcs-roots

# prometheus-pdns-exporter is scraped by cloudmetrics
# prometheus-node-exporter by prod servers
prometheus_nodes:
  - cloudmetrics1003.eqiad.wmnet
  - cloudmetrics1004.eqiad.wmnet
  - prometheus1005.eqiad.wmnet
  - prometheus1006.eqiad.wmnet

contactgroups: wmcs-team-email

cluster: wmcs
profile::prometheus::memcached_exporter::arguments: "--memcached.address=localhost:11000"
# See T224828
raid::md::timer_ensure: absent
profile::contacts::role_contacts: ["WMCS"]

profile::openstack::base::pdns::default_soa_content: ns0.openstack.eqiad1.wikimediacloud.org
