profile::prometheus::icinga_exporter::label_teams_config:
  wmcs:
    alertname:
      - '.*[cC]eph.*'
    instance:
      - '.*cloud.*'
      - '.*labs.*'

  dcops:
    # tag all but 'physical' netbox report with 'team=dcops'
    alertname:
      - '^Netbox report(?!.*physical)'

  # Taken from modules/netops/manifests/check.pp
  # monitoring::service 'description' parameter
  netops:
    alertname:
      - '^Juniper alarms'
      - '^Juniper virtual chassis ports'
      - '^Router interfaces'
      - '^(BGP|VRRP|BFD|OSPF) status'

  # this is the default team, must be the last in the definition.
  sre:
    alertname:
      - '.*'
