# Notify the Data Engineering team about services on these hosts
contactgroups: 'admins,analytics'

nagios_group: analytics_eqiad
cluster: analytics
profile::admin::groups:
  - analytics-admins

# Database password will be filled added in profile::superset from the
# profile::superset::database_password hiera variable stored in the private repo.
profile::superset::database_uri: mysql://superset_staging@an-coord1001.eqiad.wmnet/superset_staging?ssl_ca=/etc/ssl/certs/Puppet_Internal_CA.pem
profile::superset::workers: 8
profile::superset::ldap_proxy_enabled: true
profile::superset::enable_cas: true
profile::superset::server_name: 'superset-next.wikimedia.org'

profile::superset::proxy::x_forwarded_proto: 'https'
profile::superset::proxy::ferm_srange: '($CACHES $ANALYTICS_NETWORKS)'
# Disabling due to permission issue https://phabricator.wikimedia.org/T273850
# profile::superset::data_cache_uri: 'localhost'
profile::superset::metadata_cache_uri: 'localhost'
profile::superset::filter_state_cache_uri: 'localhost'
profile::superset::explore_form_data_cache_uri: 'localhost'

# TLS Terminator settings
# Please note: the service name is used to pick up the
# TLS certificate that envoy will use. Since the Analytics
# team has only one certificate for its UIs, then the service
# name listed does not reflect how the envoy proxy is set up.
# superset-next.wikimedia.org is a SAN of the yarn.wikimedia.org
# TLS certificate.
profile::envoy::ensure: present
profile::tlsproxy::envoy::services:
   - server_names: ['*']
     port: 80

profile::tlsproxy::envoy::global_cert_name: "yarn.wikimedia.org"

profile::monitoring::notifications_enabled: false

profile::kerberos::keytabs::keytabs_metadata:
  - role: 'superset'
    owner: 'superset'
    group: 'superset'
    filename: 'superset.keytab'

# Context https://phabricator.wikimedia.org/T278353#6976509
profile::kerberos::client::dns_canonicalize_hostname: false

profile::memcached::version: 'present'
profile::memcached::port: 11211
profile::memcached::size: 256
profile::memcached::extended_options:
  - 'modern'

profile::contacts::role_contacts: ['Data Engineering']

profile::puppet::agent::force_puppet7: true
acmechief_host: acmechief2002.codfw.wmnet
