profile::aptrepo::staging::basedir: /srv/aptrepo/wikimedia-staging
profile::aptrepo::staging::homedir: '/root'
profile::aptrepo::staging::gpg_user: 'root'
profile::aptrepo::staging::gpg_pubring: ~
profile::aptrepo::staging::gpg_secring: ~