profile::restbase::seeds_ng:
  - restbase2024-a.codfw.wmnet
  - restbase2024-b.codfw.wmnet
  - restbase2024-c.codfw.wmnet
  - restbase2025-a.codfw.wmnet
  - restbase2025-b.codfw.wmnet
  - restbase2025-c.codfw.wmnet
# used for rate limiting
profile::restbase::hosts:
  - restbase2013.codfw.wmnet
  - restbase2014.codfw.wmnet
  - restbase2015.codfw.wmnet
  - restbase2016.codfw.wmnet
  - restbase2017.codfw.wmnet
  - restbase2018.codfw.wmnet
  - restbase2019.codfw.wmnet
  - restbase2020.codfw.wmnet
  - restbase2021.codfw.wmnet
  - restbase2022.codfw.wmnet
  - restbase2023.codfw.wmnet
  - restbase2024.codfw.wmnet
  - restbase2025.codfw.wmnet
  - restbase2026.codfw.wmnet
  - restbase2027.codfw.wmnet
  - restbase2028.codfw.wmnet
  - restbase2029.codfw.wmnet
  - restbase2030.codfw.wmnet
  - restbase2031.codfw.wmnet
  - restbase2032.codfw.wmnet
  - restbase2033.codfw.wmnet
  - restbase2034.codfw.wmnet

lvs::realserver::realserver_ips:
  - '10.2.1.17' # restbase.svc.codfw.wmnet
