profile::base::enable_contacts: true
profile::base::core_dump_pattern:  '/var/tmp/core/core.%h.%e.%p.%t'
profile::base::unprivileged_userns_clone: false
profile::base::overlayfs: false
profile::base::additional_purged_packages: ['isc-dhcp-client']
profile::base::remote_syslog_tls_ca: "/etc/ssl/certs/wmf-ca-certificates.crt"
