profile::openldap::hostname: cloudservices2004-dev.codfw.wmnet
profile::openldap::mirror_mode: false
profile::openldap::backup: true
profile::openldap::server_id: 1
profile::openldap::master: cloudservices2004-dev.codfw.wmnet
profile::openldap::hash_passwords: SHA
profile::openldap::read_only: false
profile::openldap::certname: ldap-codfw1dev
profile::openldap::storage_backend: hdb
profile::openldap::sync_pass: none
profile::monitoring::notifications_enabled: false
profile::admin::groups:
  - wmcs-roots
  - labtest-roots
# See T224828
raid::md::timer_ensure: absent
profile::contacts::role_contacts: ['WMCS']

# prometheus-pdns-exporter is scraped by cloudmetrics
# prometheus-node-exporter by prod servers
prometheus_nodes:
    - cloudmetrics1003.eqiad.wmnet
    - cloudmetrics1004.eqiad.wmnet
    - prometheus2005.codfw.wmnet
    - prometheus2006.codfw.wmnet

profile::openstack::codfw1dev::pdns::recursor_service_name: ns-recursor.openstack.codfw1dev.wikimediacloud.org

profile::openstack::base::pdns::auth::listen_on:
  - "%{facts.ipaddress}"
  - "%{facts.ipaddress6}"
  - 185.15.57.25  # ns.openstack.codfw1dev.wikimediacloud.org

profile::openstack::base::pdns::default_soa_content: ns0.openstack.codfw1dev.wikimediacloud.org

profile::openstack::base::pdns::recursor::bgp_vip: 172.20.254.1

profile::bird::advertise_vips:
  # NOTE: this is a shared BGP-based anycast VIP. There also a non-shared per-host adddress
  ns-recursor.openstack.codfw1dev.wikimediacloud.org:
    ensure: present
    service_type: "pdns recursor"
    address: 172.20.254.1
    check_cmd: "/usr/lib/nagios/plugins/check_dns_query -H 172.20.254.1 -d www.wikimedia.org -t 1"

# TODO: override here the list of openstack controllers so communication happens
# over the cloud-private subnet. Once all openstack servers (most notably cloudnet)
# are in the same network setup, this override could probably be deleted and set more
# generally
profile::openstack::codfw1dev::openstack_controllers:
  - cloudcontrol2001-dev.private.codfw.wikimedia.cloud
  - cloudcontrol2004-dev.private.codfw.wikimedia.cloud
  - cloudcontrol2005-dev.private.codfw.wikimedia.cloud
