# General configs
cluster: logstash
profile::admin::groups:
  - logstash-roots
  - elasticsearch-roots

profile::kafka::broker::kafka_cluster_name: logging

# Enable SSL/TLS for Kafka. When using PKI (default), this requires
# only profile::kafka::broker::ssl_password committed in
# the expected location in ops/puppet/private.
profile::kafka::broker::ssl_enabled: true
profile::base::certificates::include_bundle_jks: true

# Enable basic ACL handling via Zookeeper stored rules
# More info https://phabricator.wikimedia.org/T167304#3478277
profile::kafka::broker::auth_acls_enabled: true

# Enable Monitoring (via Prometheus) and icinga alerts
profile::kafka::broker::monitoring_enabled: true
profile::kafka::broker::monitoring::is_critical: false

# (4 disks in the broker HW RAID array)
# Bump this up to get a little more parallelism between replicas.
profile::kafka::broker::num_replica_fetchers: 4
# These two values were not picked up before
# https://gerrit.wikimedia.org/r/c/operations/puppet/+/941362
# Rolling them out carefully instead of all at once.
#profile::kafka::broker::num_recovery_threads_per_data_dir: 4
#profile::kafka::broker::num_io_threads: 4

# To be changed during Kafka broker version upgrades
profile::kafka::broker::inter_broker_protocol_version: 1.1.0

profile::kafka::broker::group_initial_rebalance_delay: 10000

profile::kafka::broker::max_heap_size: '2g'
profile::kafka::broker::num_partitions: 6
profile::kafka::broker::log_retention_hours: 120

profile::base::certificates::include_bundle_jks: true

# Kafka doesn't support Java 11 for versions
# lower than 2.1
# https://issues.apache.org/jira/browse/KAFKA-7264
profile::java::java_packages:
  - version: '8'
    variant: 'jdk'

profile::contacts::role_contacts: ['Observability']
